.PHONY: 1 2 3 4 5 6 all
all: 1 2 3 4 5 6
1:
	g++ main.cc -std=c++11 -g -Din_size=1
	./a.out
2:
	g++ main.cc -std=c++11 -g -Din_size=2
	./a.out
3:
	g++ main.cc -std=c++11 -g -Din_size=3
	./a.out
4:
	g++ main.cc -std=c++11 -g -Din_size=4
	./a.out
5:
	g++ main.cc -std=c++11 -g -Din_size=5
	./a.out
6:
	g++ main.cc -std=c++11 -g -Din_size=6
	./a.out
	