.PHONY: 1 2 3 4 5 6 all
all: 1 2 3 4
1:size1/g.gv
	dot -Tpng ./size1/g.gv -o ./size1/g.png
#	dot -Tpng ./size1/sub.gv -o ./size1/sub.png
2:size1/g.gv
	dot -Tpng ./size2/g.gv -o ./size2/g.png
#	dot -Tpng ./size2/sub.gv -o ./size2/sub.png
3:size1/g.gv
	dot -Tpng ./size3/g.gv -o ./size3/g.png
#	dot -Tpng ./size3/sub.gv -o ./size3/sub.png
4:size1/g.gv
	dot -Tpng ./size4/g.gv -o ./size4/g.png
#	dot -Tpng ./size4/sub.gv -o ./size4/sub.png
5:size1/g.gv
	dot -Tpng ./size5/g.gv -o ./size5/g.png
#	dot -Tpng ./size5/sub.gv -o ./size5/sub.png
6:size1/g.gv
	dot -Tpng ./size6/g.gv -o ./size6/g.png
#	dot -Tpng ./size6/sub.gv -o ./size6/sub.png
